### ISSUE TITLE
mqtt.js returned Connection refused

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdk-node#46] opened 2017-06-06 13:39 UTC
# Context
- **OS and version used:** Ubuntu 16
- **Node.js version:** 7.1.0
- **npm version:** 3.10.9
- **list of installed packages:** 
├──azure-iot-device@1.1.12
├── azure-iot-device-mqtt@1.1.12

# Description of the issue:
When I try to send event to cloud I have started seeing ** mqtt.js returned Connection refused: Not authorized error** today. Please let me know if it is an issue with iothub or api? and How to best handle this failure. This was happening earlier due to some bug. Please confirm.

I checked the connection status and it shows disconnected. however it never emitted disconnected event.

Thanks

**Comment by Kapster17** [comment] 2017-06-06 16:12
How did you check the connection status ?
Did you use a listener ?
Will be helpful info for me.

**Comment by bmrpatel** [comment] 2017-06-06 17:39
@Kapster17 
You can use DeviceExplorer tool if you are using windows
I do use listener as well.

**Comment by Kapster17** [comment] 2017-06-06 18:06
I was looking at ways the device code (for me its on RPi) can check for a connection loss.
Currently we check for client.on('disconnect', function ()) and then call connect again....but the catch is I fail to get a call back on disconnect. I would never reconnect.
I encountered an issue when the call back for SendEvent was not firing when my wifi was switched off.
Steps to repro
1- Send Events....Call back for Send Event called.
2-Turn Off Wifi
3- Call back for Send Event not called.
4-After 5 mins I get a call back to Disconnect....on windows this is much faster < 1 min I get a call to Disconnect

**Comment by pierreca** [comment] 2017-06-06 18:30
The connection status that you get from the registry is eventually correct but not real-time. it is not a good way to verify that the device is actually connected. 

connection refused feels like a timed out shared access signature or another device connected with the same connection string - most probably the first one. 

Are you creating the client with `Client.fromSharedAccessSignature()` or with `Client.fromConnectionString()`?

Also I'd suggest enabling debug traces if the problem reproduces on a regular basis. if it doesn't and is now over, i'll need the iot hub name, device id and timestamp to look if I can see something in the logs

**Comment by bmrpatel** [comment] 2017-06-08 12:51
@pierreca I am using `Client.fromConnectionString()`. Do you think I should be using the `Client.fromSharedAccessSignature()`?

Please send me your contact info and I will send you the connection details and timestamp, so you can check the log. It only happens with few of the devices running the latest 1.1.12. It could be coincident and issue may be the poor network on site.

Thanks

**Comment by pierreca** [comment] 2017-06-08 23:42
it's a weird error if the problem is poor connectivity... 
the difference between `fromConnectionString()` and `fromSharedAccessSignature()` is that `fromConnectionString()`  manages the expiration of the shared access signature for you, and disconnects/reconnects the device with a new SAS every 45 minutes, while with `fromSharedAccessSignature()`, you generate the SAS yourself, and you can set whatever expiration you want. so if you have devices that reboot or sleep/wake up on a regular basis for example, you could create a SharedAccessKey for the duration of the uptime everytime, and never rely on our 45-minute SAS renewal mechanism. It feels like this is what might be going on.

**Comment by pierreca** [comment] 2017-10-25 03:20
@bmrpatel 

we've introduced a retry logic in the latest release that should help with connectivity issue - you should try to update to our latest version and let us know if the problem persists:

- https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-10-24
- https://www.npmjs.com/package/azure-iot-device (`azure-iot-device@1.2.0`)

Closing since this is old and probably fixed - feel free to reopen (or better, open a new issue with updated observations) if you still run into the problem.

**Closed by pierreca** 2017-10-25 03:20 UTC
Labels: help wanted
