### ISSUE TITLE
cloud to device communication using https and amqp protocols getting failed 

### ISSUE THREAD

**Issue by sharathbaddam** [Azure/azure-iot-sdk-node#27] opened 2017-03-31 19:16 UTC
Hi there!

I've been using cloud to device and device to cloud communication using https, amqp and mqtt for months now.
I have not changed anything in my code, but I'm getting this error when i try to register device and open a connection with amqp and https from this morning :- 

{ Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGN
ATURE' }
# Context
- **OS and version used:** Windows 7
- **Node.js version:** node version 6.9.5
- **npm version:** 3.10.6

Any help is appreciated. thanks

**Comment by pierreca** [comment] 2017-03-31 21:53
Hi, can you let us know what your IoT Hub name is?
Also, which version of the SDK packages are you using?

**Comment by pierreca** [comment] 2017-03-31 22:39
Looks like the device might be unable to verify our certificate. I wonder if it could be that some network or security configuration changed (either the list of Root CA on your machine or on a proxy you'd be using?

**Comment by anthonyvercolano** [comment] 2017-03-31 22:45
Also, just to clarify.  You're seeing this issue trying to exclusively do service side operations?  So your connection string (do NOT post it) was for your actual hub, not a particular device?

**Comment by sharathbaddam** [comment] 2017-04-03 20:03
Hello @pierreca @anthonyvercolano, I did more debugging and found that I'm actually getting this error when i try to register the device. it is not specific to amqp or https. Usually whenever I start to receive messages from IOT, I register the device. If I get an error that says if the device is already registered, I'm getting the device key.

My IOT hub name is 'IOTtest6777'.
here are my dependencies list :-  
     `    

         "azure-event-hubs":` "0.0.7",
         "azure-iot-device": "1.1.8",
         "azure-iot-device-amqp": "1.1.8",
         "azure-iot-device-http": "1.1.8",
         "azure-iot-device-mqtt": "1.1.8",
         "azure-iothub": `"1.1.8", `
here is the snippet of my code for registration:- 

     // options is object with connection string (HostName=IOTtest6777.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey='....') and DeviceId
    let registry: iothub.Registry = iothub.Registry.fromConnectionString(options.connectionString);
    let device: iothub.Device = new iothub.Device();
    device.deviceId = options.DeviceId;
    registry.create(device, (error: NodeJS.ErrnoException, deviceInfo: iothub.Device) => {
      if (error) {
        if (error.message.includes('already registered')) {
          registry.get(device.deviceId, (errorr: NodeJS.ErrnoException, devicedata: iothub.Device) => {
             if(!errorr) {
                let deviceKey: string = devicedata['authentication']['symmetricKey']['primaryKey'];
                let devconnectionString: string = 'HostName=' + regOptions.HostName + ';DeviceId=' + regOptions.DeviceId +';SharedAccessKey=' + deviceKey;
                console.log(devconnectionString);
             } else {
                console.log(errorr);
             }
          });
        } else {
             console.log(error);
        }
      } else {
        let deviceKey: string = deviceInfo['authentication']['symmetricKey']['primaryKey'];
        let devconnectionString: string = 'HostName=' + regOptions.HostName + ';DeviceId=' + regOptions.DeviceId +';SharedAccessKey=' + deviceKey;
        console.log(devconnectionString);
       }
     });`

**Comment by anthonyvercolano** [comment] 2017-04-04 20:32
Also, can you tell me a little more about your networking environment.  Are you on a controlled corporate network or does the device have a direct internet connection?

Also, If I may, there is a web article https://connectedstuff.io/2017/03/16/cross-platform-iot-mac-part3/

This details how to run node diagnostic program.  If you could try it on the windows 7 machine that is experiencing this issue perhaps it might reveal something.

**Comment by sharathbaddam** [comment] 2017-04-04 20:54
Yes I'm in a corporate network, and yes the device have a wired internet connection.

I looked into the article you suggested and ran iot hub diagnostics, here is the output :- 


2017-04-04T20:46:56.533Z - info: *******************************************
2017-04-04T20:46:56.533Z - info: * Executing the Microsoft IOT Trace tool. *
2017-04-04T20:46:56.533Z - info: *******************************************
2017-04-04T20:46:56.533Z - info:
2017-04-04T20:46:56.549Z - info: --- Executing network tests ---
2017-04-04T20:46:56.667Z - info:
2017-04-04T20:46:56.667Z - info: Starting DNS resolution for host 'www.microsoft.com'...
2017-04-04T20:46:56.671Z - info: --> Successfully resolved DNS to 104.108.56.152.
2017-04-04T20:46:56.671Z - info:
2017-04-04T20:46:56.671Z - info: Pinging IPV4 address '104.108.56.152'...
2017-04-04T20:46:56.924Z - info: --> Successfully pinged 104.108.56.152
2017-04-04T20:46:56.924Z - info:
2017-04-04T20:46:56.924Z - info: Sending https request to 'https://www.microsoft.com/'
2017-04-04T20:46:57.403Z - info: --> Completed https request
2017-04-04T20:46:57.419Z - info:
2017-04-04T20:46:57.419Z - info: --- Executing IOT Hub tests ---
2017-04-04T20:47:00.525Z - info:
2017-04-04T20:47:00.540Z - info: Starting AMQP Test...
2017-04-04T20:47:05.536Z - info: --> Successfully ran AMQP test.
2017-04-04T20:47:05.536Z - info:
2017-04-04T20:47:05.536Z - info: Starting AMQP-WS Test...
2017-04-04T20:47:09.503Z - info: --> Successfully ran AMQP-WS test.
2017-04-04T20:47:09.581Z - info:
2017-04-04T20:47:09.581Z - info: Starting HTTPS Test...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)

C:\Users\sbaddam>


I ran it multiple times but I got same error at different levels, few times I got error when it is running AMQP and AMQP-WS tests, but never passed all the tests.

**Comment by anthonyvercolano** [comment] 2017-04-04 23:58
My biggest suspicion at this point is that recently someone on the PARTICULAR windows 7 machine, or perhaps on your corporate network has changed some proxy settings.  Or perhaps on the corporate network there are some new packet inspections occurring.

Any chance you have some corporate IT resources who could provide some insight into any recent corporate proxy changes?

By the way are you sure that you got AMQP connection errors?  Or was it really AMQPWS (websockets)  errors?

**Comment by sharathbaddam** [comment] 2017-04-05 02:46
Sure, I will ask IT about any recent changes in network.

I got error couple of times just before starting AMQP. But most of the times it stopped at HTTPS test.

**Comment by sharathbaddam** [comment] 2017-04-05 02:47
By the way, I got same error when tested it on same Win 7 machine from home, not connected to vpn.

**Comment by anthonyvercolano** [comment] 2017-04-05 23:16
Ok, this part is a little involved:

I presume you cloned the iothub-diagnostic project?  If so, go to the config directory and edit index.js  at line 15 replace the httpsRequestUrl with: 'https://IOTtest6777..azure-devices.net/sharathbaddamendpoint'

Then in the ..\networktests directory, in the file index.js insert the following two lines at line 46 of the httpsRequest function:
   console.log('status code: ',res.statusCode);
    console.log('headers: ', res.headers);

run the diagnostic again.  No need to give it the iothub connection string.
Let me know what you see.

I'm thinking you'll see the leaf error.

**Comment by sharathbaddam** [comment] 2017-04-06 14:33
Here is the report :- 

2017-04-06T14:31:11.190Z - info: *******************************************
2017-04-06T14:31:11.195Z - info: * Executing the Microsoft IOT Trace tool. *
2017-04-06T14:31:11.196Z - info: *******************************************
2017-04-06T14:31:11.197Z - info:
2017-04-06T14:31:11.197Z - info: --- Executing network tests ---
2017-04-06T14:31:11.279Z - info:
2017-04-06T14:31:11.280Z - info: Starting DNS resolution for host 'www.microsoft.com'...
2017-04-06T14:31:11.306Z - info: --> Successfully resolved DNS to 23.46.56.194.
2017-04-06T14:31:11.307Z - info:
2017-04-06T14:31:11.307Z - info: Pinging IPV4 address '23.46.56.194'...
2017-04-06T14:31:11.432Z - info: --> Successfully pinged 23.46.56.194
2017-04-06T14:31:11.432Z - info:
2017-04-06T14:31:11.433Z - info: Sending https request to 'https://IOTtest6777.azure-devic
es.net/sharathbaddamendpoint'
status code:  404
headers:  { 'content-length': '0',
  server: 'Microsoft-HTTPAPI/2.0',
  date: 'Thu, 06 Apr 2017 14:31:11 GMT',
  connection: 'close' }

**Comment by anthonyvercolano** [comment] 2017-04-06 17:04
Yet, if you include the hub connnection string you'll still get a failure?

**Comment by anthonyvercolano** [comment] 2017-04-06 17:12
Also, can you try to do this registry operation from any other machine and does it work?

**Comment by sharathbaddam** [comment] 2017-04-10 15:37
Yeah, it still fails with connection string, I would have to try it in my personal system and check if i'm having same problem.

**Comment by tameraw** [comment] 2017-04-26 21:01
@sharathbaddam - Are you still having issues here? We tried on a Windows 7 and could not reproduce the error you're seeing.

**Comment by tameraw** [comment] 2017-05-01 17:19
@sharathbaddam - Closing. Feel free to reopen if still having issues.

**Closed by tameraw** 2017-05-01 17:19 UTC
Labels: help wanted
