### ISSUE TITLE
AMQP stops receiving messages

### ISSUE THREAD

**Issue by jtjk** [Azure/azure-iot-sdk-node#110] opened 2017-10-18 07:28 UTC
# Context
- **OS and version used:** Debian Linux (Beaglebone Black) newest version
- **Node.js version:** 8.6.0
- **npm version:** 5.3.0
- **list of installed packages:** 
    "azure-iot-device": "^1.1.19",
    "azure-iot-device-amqp": "^1.2.0",
    "mathjs": "~1.4.0",
    "mongoose": "^4.5.8",
    "winston": "^3.0.0-rc0"

# Description of the issue:
AMQP stops receiving messages. First it works very well, but then something happens and it stops working. It was working very well with node 4.8.4, but it is time to say goodbye for that node version. When reconnecting it might still be broken, but suddenly missing messages might come again. Sometimes it needs multiple reconnection trials.

# Code sample exhibiting the issue:
Very much similar to simple sample

# Console log of the issue:
Wed, 18 Oct 2017 07:09:19 GMT amqp10:framing => (EMPTY FRAME)
Wed, 18 Oct 2017 07:09:19 GMT amqp10:trace raw: [0000000802000000]
Wed, 18 Oct 2017 07:09:49 GMT azure-iot-device.Client Client state change: connected -> updating_sas (action: connected.updateSharedAccessSignature)
2017-10-18T07:09:49.992Z amqp-common:senderlink pushing message to pending queue
2017-10-18T07:09:49.997Z amqp-common:senderlink sending message using underlying amqp10 link object
Wed, 18 Oct 2017 07:09:49 GMT amqp10:link:sender canSend(98,4906) = true
Wed, 18 Oct 2017 07:09:50 GMT amqp10:link:sender sending:  AmqpMessage {
  applicationProperties:
   { operation: 'put-token',
     type: 'servicebus.windows.net:sastoken',
     name: 'lightdna.azure-devices.net%2Fdevices%2FBeagleOffice' },
  body: 'SharedAccessSignature sr=lightdna.azure-devices.net%2Fdevices%2FBeagleOffice&sig=WfsnipsnipsnipxCtFC0XQ%3D&se=150snip90',
  properties:
   { to: '$cbs',
     messageId: '402a1195-fe68-4af8-a9b4-1d74ad9127b2',
     reply_to: 'cbs' } }
Wed, 18 Oct 2017 07:09:50 GMT amqp10:framing => @transfer(20) [handle=0 deliveryId=596 deliveryTag=<Buffer 35 39 36> messageFormat=0 settled=false more=false rcvSettleMode=0 state=null resume=false aborted=false batchable=false]
Wed, 18 Oct 2017 07:09:50 GMT amqp10:trace raw: [0000017302000001005314c0150b437000000254a003353936434242500040424242005373c0380da12434303261313139352d666536382d346166382d613962342d31643734616439313237623240a1042463627340404040404040404040005374c17906a1096f7065726174696f6ea1097075742d746f6b656ea10474797065a11f736572766963656275732e77696e646f77732e6e65743a736173746f6b656ea1046e616d65a1336c69676874646esnip617a7572652d646576696365732e6e657425324664657669636573253246426561676c654f6666696365005377a1915368617265644163636573735369676e61747572652073723d6c69676874646e612e617a7572652d646576696365732e6e657425324664657669636573253246426561676c654f6666696365267369673d576675253246756e532532464c33623349506558334c35434248556c6b36706c616d5054754d5078437446433058512533442673653d31353038333134313930]
Wed, 18 Oct 2017 07:09:50 GMT amqp10:trace Rx: 0000001b02000000005315c00e0641700000025440410053244540
Wed, 18 Oct 2017 07:09:50 GMT amqp10:framing <= @disposition(21) [role=true first=596 last=null settled=true state=@accepted(36) [] batchable=false]
Wed, 18 Oct 2017 07:09:50 GMT amqp10:trace raw: [005315c00e0641700000025440410053244540]
2017-10-18T07:09:50.074Z amqp-common:senderlink message sent successfully
Wed, 18 Oct 2017 07:09:50 GMT amqp10:trace Rx: 0000008b02000000005314c0160b52017000000255a004030000004340424040404042005373c0330d4040404040a12434303261313snip52d666536382d346166382d613962342d31643734616439313237623240404040404040005374c12b04a10b7374617475732d636f646571000000c8a1127374617475732d6465736372697074696f6ea1024f4b
Wed, 18 Oct 2017 07:09:50 GMT amqp10:framing <= @transfer(20) [handle=1 deliveryId=597 deliveryTag=<Buffer 03 00 00 00> messageFormat=0 settled=null more=false rcvSettleMode=0 state=null resume=false aborted=false batchable=false]
Wed, 18 Oct 2017 07:09:50 GMT amqp10:trace raw: [005314c0160b52017000000255a004030000004340424040404042005373c0330d4040404040a12434303261313139352d666536382d3461snip3962342d31643734616439313237623240404040404040005374c12b04a10b7374617475732d636f646571000000c8a1127374617475732d6465736372697074696f6ea1024f4b]
Wed, 18 Oct 2017 07:09:50 GMT amqp10:link:receiver Rx message 597 on $cbs_b2db35d4-201e-4d76-8123-c9080e7d3eed, 97 credit, 302 window left.
Wed, 18 Oct 2017 07:09:50 GMT amqp10:link:receiver received from ($cbs_b2db35d4-201e-4d76-8123-c9080e7d3eed): undefined
Wed, 18 Oct 2017 07:09:50 GMT amqp10:framing => @disposition(21) [role=true first=597 last=597 settled=true state=@accepted(36) [] batchable=false]
Wed, 18 Oct 2017 07:09:50 GMT amqp10:trace raw: [0000001f02000001005315c012064170000002557000000255410053244542]
Wed, 18 Oct 2017 07:09:50 GMT azure-iot-device.Client sas token updated; needToReconnect: false
Wed, 18 Oct 2017 07:09:50 GMT azure-iot-device.Client Client state change: updating_sas -> connected (action: )
Wed, 18 Oct 2017 07:11:35 GMT amqp10:trace Rx: 0000000802000000
Wed, 18 Oct 2017 07:11:35 GMT amqp10:framing <= (EMPTY FRAME)
Wed, 18 Oct 2017 07:11:35 GMT amqp10:trace raw: [0000000802000000]

Wed, 18 Oct 2017 07:12:19 GMT amqp10:framing => (EMPTY FRAME)
Wed, 18 Oct 2017 07:12:19 GMT amqp10:trace raw: [0000000802000000]
^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[Bi
Wed, 18 Oct 2017 07:13:20 GMT amqp10:trace Rx: 0000000802000000
Wed, 18 Oct 2017 07:13:20 GMT amqp10:framing <= (EMPTY FRAME)
Wed, 18 Oct 2017 07:13:20 GMT amqp10:trace raw: [0000000802000000]

Wed, 18 Oct 2017 07:14:19 GMT amqp10:framing => (EMPTY FRAME)
Wed, 18 Oct 2017 07:14:19 GMT amqp10:trace raw: [0000000802000000]

Wed, 18 Oct 2017 07:15:05 GMT amqp10:trace Rx: 0000000802000000
Wed, 18 Oct 2017 07:15:05 GMT amqp10:framing <= (EMPTY FRAME)
Wed, 18 Oct 2017 07:15:05 GMT amqp10:trace raw: [0000000802000000]

^[[B^[[BWed, 18 Oct 2017 07:16:19 GMT amqp10:framing => (EMPTY FRAME)
Wed, 18 Oct 2017 07:16:19 GMT amqp10:trace raw: [0000000802000000]
Wed, 18 Oct 2017 07:16:50 GMT amqp10:trace Rx: 0000000802000000
Wed, 18 Oct 2017 07:16:50 GMT amqp10:framing <= (EMPTY FRAME)
Wed, 18 Oct 2017 07:16:50 GMT amqp10:trace raw: [0000000802000000]

**Comment by pierreca** [comment] 2017-10-18 20:37
So if I understand correctly what you're saying, after renewing the shared access signature, the cloud-to-device messages (sent from a service to a device) are not received anymore? and it takes multiple reconnection attempts to get them again?

**Comment by jtjk** [comment] 2017-10-19 04:33
Yeah. It lookslike that. I am not renewing anything but the sdk is

**Comment by pierreca** [comment] 2017-10-19 05:22
I can see in your traces that the CBS update happens correctly without disconnecting the transport. I'm wondering whether we have an `EventEmitter` that is disconnected in specific conditions... What makes me wonder is that we have e2e tests for that and they always pass. so either the issue is systematic and our e2e tests are not written properly, or is temporary and in that case I'll try and set up a local repro to look at service logs at the same time.

how often do you see the problem? every 45 minutes? or is it only occasional?

**Comment by jtjk** [comment] 2017-10-19 05:55
I guess it is almost every 45 minutes. Sometimes maybe even faster and sometimes it might work over night.

I can run the same code without problems in my Mac with same node version. This might be Linux related.

**Comment by jtjk** [comment] 2017-10-24 16:07
with the retry logic preview, I have been now running 10 hours without problems. I have fingers crossed and I hope that it will stay up overnight :)

**Comment by pierreca** [comment] 2017-10-24 23:12
great, I will release those packages very soon. please do keep us posted!

**Comment by pierreca** [comment] 2017-10-25 02:45
Packages have been released: 

- https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-10-24
- https://www.npmjs.com/package/azure-iot-device

Please do let us know how it turned out.

**Comment by pierreca** [comment] 2017-11-03 19:10
@jtjk Closing since the packages have been released and the issue is idle. if you run into the same issue again please reopen it, or create a new one. Thanks!

**Closed by pierreca** 2017-11-03 19:10 UTC
Labels: bug, fix checked in
