### ISSUE TITLE
NotConnectedError: getaddrinfo ENOTFOUND <hostName><hostName>:8883

### ISSUE THREAD

**Issue by AndyChuang1** [Azure/azure-iot-sdk-node#494] opened 2019-02-20 09:22 UTC
# Context
- **OS and version used:**  Ubuntu 16.04.05.  
- **Node.js version:** v8.15.0 
- **npm version:** 6.4.1
- **list of installed packages:** <VERSION> {
    "azure-iot-device": "1.9.3",
    "azure-iot-device-mqtt": "1.9.3",
    "cookie-parser": "~1.4.3",
    "crypto-token": "^1.0.1",
    "debug": "~2.6.9",
    "default-gateway": "^3.0.1",
    "express": "~4.16.0",
    "formidable": "^1.2.1",
    "fs-extra": "^7.0.1",
    "http-errors": "~1.6.2",
    "jade": "~1.11.0",
    "morgan": "~1.9.0",
    "network-config": "^2.0.0",
    "passwd-linux": "^2.0.0",
    "ejs": "^2.6.1"
  }

# Description of the issue:
I'm using azure-iot-device & azure-iot-device-mqt for azure iot edge right now.
I followed the official docs to create node module.
Node app always threw this error which is `NotConnectedError: getaddrinfo ENOTFOUND ecs-aplu-ic1 ecs-aplu-ic1:8883`  when node app connected to the Edge instance.
# Code sample exhibiting the issue:
```
var Transport = require('azure-iot-device-mqtt').Mqtt;
var Client = require('azure-iot-device').ModuleClient;
var Message = require('azure-iot-device').Message;
var moduleClient;
Client.fromEnvironment(Transport, function (err, client)
 {
        if (err) {
            throw err;
        } else {
            moduleClient = client;
            client.on('error', function (err) {
                throw err;
            });
            // connect to the Edge instance
            client.open(function (err) {
                if (err) {
                    throw err;
                } else {
                    console.log('IoT Hub module client initialized');
                    // Act on input messages to the module.
                    client.on('inputMessage', function (inputName, msg) {
                        filterMessage(client, inputName, msg);
                    });
                }
            });
        }
    });
```

# Console log of the issue:
![Imgur](https://i.imgur.com/1T0IOHp.png)
# My temporary Solution 
My host name is ecs-APLU-IC1, as below:
![Imgur](https://i.imgur.com/ZWyLLY1.png)
If I edit hosts file ,change ecs-APLU-IC1 to ecs-aplu-ic1, this error will not happen.
Is that Case converter issue of SDK ?

**Comment by anthonyvercolano** [comment] 2019-02-20 19:50
Thank you for reporting this problem!

If I could ask, could you refile this as an issue in https://github.com/Azure/iotedge ?

We are fairly certain where the problem is in that code base.  By refiling it, we can track it better and report back when a fix is released.

**Comment by darobs** [comment] 2019-02-20 20:46
Hello @AndyChuang1,

When the Azure IoT Edge sends the gateway hostname to the module, we set the hostname to all lowercase. You can see the code [here](https://github.com/Azure/iotedge/blob/master/edgelet/iotedged/src/lib.rs#L877).  The SDK is picking up what the Edge is setting, and the lowercase hostname is not being found in /etc/hosts.

Normally, these kinds of issues are resolved via DNS, which generally is case-insensitive. 

A quick fix to the problem may be to add the lowercase name as an alias:
127.0.1.1 ecs-APLU-IC1 ecs-aplu-ic1

**Comment by AndyChuang1** [comment] 2019-02-21 01:09
@anthonyvercolano Thank you for your reply, I will refile it in [Azure IOT Edge](https://github.com/Azure/iotedge)

**Comment by myagley** [comment] 2019-02-21 16:37
I'm not necessary convinced the issue is in the IoT Edge codebase. As mentioned, the C#, python, and C SDKs can resolve hostnames as case insensitive. How does the node SDK resolve hostnames?

**Comment by pierreca** [comment] 2019-03-13 21:56
node is definitely capable of resolving names without being case sensitive at least locally. I just did quick PoC outside of edge with a local HTTP server and entry in /etc/hosts and it worked without any problem.
next test is to try from within a container running on the iot-edge docker network

**Comment by pierreca** [comment] 2019-03-14 17:22
update: running inside an ubuntu 16.04 container works as well.

@AndyChuang1 would you mind letting us know:
- where is the code that has trouble resolving running (container or host)
- what OS is that code running on (is Ubuntu 16.04 your host OS or your container image? which container image are you using if not Ubuntu 16.04?)
- this /etc/hosts file, is it on the host or in the container?
in short, can you precisely describe all the OSes, container images and network config involved?

**Comment by pierreca** [comment] 2019-03-19 01:23
Closing given @AndyChuang1  seems to have seen the last message (thumbs up) and there's nothing we can do on the SDK side to address this.

**Comment by az-iot-builder-01** [comment] 2019-03-19 01:23
@darobs, @AndyChuang1, @myagley, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-03-19 01:23 UTC
Labels: investigation-required

**Comment by AndyChuang1** [comment] 2019-03-19 01:26
@pierreca 
Sorry about response late.
1.  host
2. My code is running on container image (node:8-alpine).
3. I modified /etc/hosts on Host.  **My host os is Ubuntu 16.04.05** .Container images is node-alpine as I said. network config id just DHCP.
Thank you for your investigation~!!
