### ISSUE TITLE
azure-iot-device-mqtt cloud to device message listening stops after ~2 days.

### ISSUE THREAD

**Issue by komalpharate** [Azure/azure-iot-sdk-node#340] opened 2018-07-26 05:37 UTC
After restarting the node server it gets the queued messages if any. And start working normally. 

I have added a fix of calling client.open in interval of 5 hours. 

But I think this should not happen right?

Node v8-10
using:
https://www.npmjs.com/package/azure-iot-device-mqtt

Thank you.

**Comment by anthonyvercolano** [comment] 2018-07-26 16:35
Hello,

  Thank you for reaching out.

  If we could get a little more info.
  What version of the azure-iot-device-mqtt package are you using?
  What OS is being used?
  Does this reliably reproduce?  We realize this is a bit painful with a problem that takes 2 days to occur.
  Is it possible to generate logs?  Setting the DEBUG environment variable to "azure*" will produce a lot of good information about what is going on.
  The opening post of the issue just lists azreu-iot-device-mqtt.  Is the azure-iot-device package being utilized as well?

**Comment by pierreca** [comment] 2018-08-03 23:05
@komalpharate ping? is there a way for you to collect the info that @anthonyvercolano  is asking for? thanks!

**Comment by pierreca** [comment] 2018-08-09 01:34
closing for lack of context & information. feel free to add more info and we will reopen it. thanks!

**Comment by az-iot-builder-01** [comment] 2018-08-09 01:34
@komalpharate, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)

**Comment by komalpharate** [comment] 2018-08-23 04:54
Hi,
Apologies for delayed reply.

What version of the azure-iot-device-mqtt package are you using?
-azure mqtt IoThub - 1.4.1

What OS is being used?
-OS - ubuntu 16.04

Does this reliably reproduce? We realize this is a bit painful with a problem that takes 2 days to occur.
-Yes I was able to reproduce this many times. As I'm working with this setup since past 6months.

Is it possible to generate logs? Setting the DEBUG environment variable to azure* will produce a lot of good information about what is going on.
Okay will check this.

Code - 
```

var clientFromConnectionString = require('azure-iot-device-mqtt').clientFromConnectionString;
var client;

registry.create(device, function (err, deviceInfo, res) {
	if (err) {
	    registry.get(device.deviceId, function (err, deviceInfo, res) {
		console.log("Device Already Registered");
		deviceConnectionString = <creationOfDeviceConnectionString>;
		client = clientFromConnectionString(deviceConnectionString);
	    });
	}

	if (res) console.log(' status: ' + res.statusCode + ' ' + res.statusMessage);
	if (deviceInfo) {
	    deviceConnectionString = <creationOfDeviceConnectionString>;
	    client = clientFromConnectionString(deviceConnectionString);
	}
});

//ConnectionCode
client.open(function (error) {
        if (error)
            console.log("Error in connecting IOTHub..");
        else {
            console.log("Connected to IOTHub");
	}
});
client.on('errorReceived', function(err){
console.log("errorreceived");
});
client.on('error', function (err) {
console.error(err.message);
});
client.on('disconnect', function () {
console.log("Disconnected");
});

client.on('message', function (message) {
  client.complete(message, printResultFor('completed'));
}

```
The opening post of the issue just lists azure-iot-device-mqtt. Is the azure-iot-device package being utilized as well?
-azure-iot-device package I have used but not for this implementation.

**Comment by pierreca** [comment] 2018-08-23 19:27
@komalpharate thanks, i've reopened the issue.
If you can get those, logs would be tremendously helpful.

does any of the error/disconnect handlers get called?

**Comment by sandysalunke** [comment] 2018-08-24 06:27
I am facing the similar issue with MQTT connection being closed/standby/ideal after 2 days. There is no **disconnect** event received on device and I am not able to send commands from Cloud to my device.

I did check this [ticket](https://github.com/Azure/azure-iot-sdk-node/issues/12), its saying the issue is fixed and available in/later than **1.1.4** version of **azure-iot-device-mqtt**. I crossed checked my dependencies and I am pointing to the latest version of it i.e. **"azure-iot-device-mqtt": "^1.1.8"**

I am not sure if the issue is really fixed and thoroughly tested by Microsoft. Can someone please update this ticket with the progress?

Environment details as follow:
- azure mqtt IoThub - 1.4.1
- OS - ubuntu 16.04
- Its reliably reproduced couple of times

**Comment by komalpharate** [comment] 2018-08-25 07:29
Hi
I'm not able to catch those disconnect event or errorReceived events with the above mentioned code.

About debug logs - will report soon as it will take time to reproduce. Will reproduce it probably on coming Wednesday (India)

**Comment by bragma** [comment] 2018-11-26 10:11
Same problem here. I am not sure the "2 days" part is an important detail. I think it's simply a case of the client being disconnected and not detecting it. D2C messages keep getting queued and the client will not be notified of a disconnection. It is a serious issue... :(

https://github.com/Azure/azure-iot-sdk-node/issues/352

**Comment by chrisahardie** [comment] 2019-02-16 21:48
I was about to create my own ticket, but this one appears to be related to the same issue. I am using the `amqp` client, but the connection does indeed consistently drop after about 2 days. Note my device only receives C2D messages, and never sends, FWIW.

OS: Raspian 9.6 Stretch
"azure-iot-device": "^1.8.2",
"azure-iot-device-amqp": "^1.8.2",

I have reduced created a script to test this issue:

```
import logger from "./src/logger";
import config from "./src/config";

// use factory function from AMQP-specific package
var clientFromConnectionString = require("azure-iot-device-amqp")
  .clientFromConnectionString;

// AMQP-specific factory function returns Client object from core package
var client = clientFromConnectionString(config.iotHubConnectionString);

var connectCallback = function(err) {
  if (err) {
    logger.error(
      "Could not connect, will attempt to reconnect in 5 seconds: ",
      err
    );
    setTimeout(() => client.open(connectCallback), 5000);
  } else {
    logger.info("client connected to iot hub");

    client.on("message", function(msg) {
      logger.info("received message");

      client.complete(msg, function() {
        logger.info("acknowledging receipt of C2D message");
      });
    });

    client.on("error", function(err) {
      logger.error(err.message);
    });

    client.on("disconnect", function() {
      logger.warn("Disconnected from IOT hub, attempting to reconnect.");
      client.removeAllListeners();
      client.open(connectCallback);
    });
  }
};

client.open(connectCallback);
setInterval(
  () =>
    logger.info(
      `${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`
    ),
  300000 //5 minutes
);
```

Note I write to the log every 5 minutes, which assured me the script wasn't hanging. I have the following abridged logs:

```
2019-02-15T00:58:54.172Z - info: client connected to iot hub
2019-02-15T00:58:54.497Z - info: received message
2019-02-15T00:58:54.535Z - info: acknowledging receipt of C2D message
2019-02-15T00:59:51.813Z - info: received message
2019-02-15T00:59:51.832Z - info: acknowledging receipt of C2D message
2019-02-15T01:00:19.549Z - info: received message
2019-02-15T01:00:19.563Z - info: acknowledging receipt of C2D message
2019-02-15T01:03:50.069Z - info: 2019-2-14 20:03:50
2019-02-15T01:08:50.100Z - info: 2019-2-14 20:08:50
2019-02-15T01:13:50.130Z - info: 2019-2-14 20:13:50
2019-02-15T01:18:50.168Z - info: 2019-2-14 20:18:50
2019-02-15T01:23:50.199Z - info: 2019-2-14 20:23:50
...
2019-02-16T00:26:44.899Z - info: received message
2019-02-16T00:26:44.912Z - info: acknowledging receipt of C2D message
2019-02-16T00:27:55.713Z - info: received message
2019-02-16T00:27:55.727Z - info: acknowledging receipt of C2D message
2019-02-16T00:28:56.287Z - info: 2019-2-15 19:28:56
2019-02-16T00:33:56.305Z - info: 2019-2-15 19:33:56
2019-02-16T00:38:56.318Z - info: 2019-2-15 19:38:56
2019-02-16T00:39:05.880Z - warn: Disconnected from IOT hub, attempting to reconnect.
2019-02-16T00:39:06.757Z - info: client connected to iot hub
2019-02-16T00:43:56.348Z - info: 2019-2-15 19:43:56
2019-02-16T00:48:56.379Z - info: 2019-2-15 19:48:56
2019-02-16T00:53:56.408Z - info: 2019-2-15 19:53:56
2019-02-16T00:58:56.425Z - info: 2019-2-15 19:58:56
2019-02-16T01:03:56.449Z - info: 2019-2-15 20:03:56
2019-02-16T01:08:56.478Z - info: 2019-2-15 20:08:56
2019-02-16T01:13:56.508Z - info: 2019-2-15 20:13:56
2019-02-16T01:14:13.323Z - warn: Disconnected from IOT hub, attempting to reconnect.
2019-02-16T01:14:14.130Z - info: client connected to iot hub
2019-02-16T01:18:56.540Z - info: 2019-2-15 20:18:56
2019-02-16T01:23:56.560Z - info: 2019-2-15 20:23:56
...
2019-02-16T20:49:10.892Z - info: 2019-2-16 15:49:10
2019-02-16T20:54:10.945Z - info: 2019-2-16 15:54:10
```

Nothing is written to the error log.

@anthonyvercolano I'll try to generate logs per your instruction above and report back.

**Comment by anthonyvercolano** [comment] 2019-02-19 17:45
@chrisahardie It would actually be best for you to raise this as a separate issue.  Include everything you have in your post.  In addition, could raise a support request?  If you do, have the support engineer direct it to me.  It will get to me.  Please make sure that they have the IoT Hub name and the device id.  Do NOT post them here.  We value your privacy.   With that information we can look up in logs on the service side to see if there was anything there that would help us.

Note also that there were fixes in the underlying AMQP layer that were brought in on the December 18, 2018 release that might mitigate this problem.   You might even consider the most current release.

Thank you.

**Comment by chrisahardie** [comment] 2019-02-19 22:33
@anthonyvercolano Thanks for your feedback. I've updated to the most current release, and have just restarted my device. I'll monitor the situation and if the issue persists, I'll open a new ticket. Thanks again!

**Comment by anthonyvercolano** [comment] 2020-01-09 00:32
This is quite old.  We never had a chance to examine error logs.  If this comes back and can be reliably reproduced, reopen this or open a new issue.

To get logs please have the environment set with DEBUG="azure*"

**Closed by anthonyvercolano** 2020-01-09 00:32 UTC
Labels: investigation-required
