### ISSUE TITLE
[Technical Question] Stress Testing D2C messages to IoT Hub

### ISSUE THREAD

**Issue by gitnwana** [Azure/azure-iot-sdk-node#1077] opened 2021-11-24 16:28 UTC
I am trying to stress test my IoT Hub which is on S1 Standard Plan. I am using NodeJS SDK to send messages at a very fast rate (multiple times over a millisecond) over the Http protocol.

The issue I am facing is after a certain number of messages being sent, the script throws an error : "ETIMEDOUT" with an IP.

I tried the same over Mqtt protocol, there I am getting "Message not Acknowledged" error. The codebase I am using is the one provided by Microsoft themselves.

Any help appreciated! Thanks

**Comment by danhellem** [comment] 2021-11-29 17:14
@gitnwana can you provide some code samples or some details? How many messages are you sending? How often? At what point do you start receiving errors?

**Comment by gitnwana** [comment] 2021-11-29 17:23
@danhellem , Hey Dan, The samples I am using are the ones provided in this repo [here](https://github.com/Azure/azure-iot-sdk-node/blob/main/device/samples/javascript/simple_sample_device.js).

As for the messages count and frequency , I just tweaked the above code to send messages every 0.01milliseconds instead of 1 second. So there's no specific count. It's just a barrage of messages continuously. 

Point of error -  after receiving somewhat ~ 10-15K over HTTP protocol , I got the ETIMEDOUT error. For MQTT - it went till around 100,000 after which I was getting the "Message not Acknowledged" error. 

IOT Hub Configuration - During both scenarios , IoT Hub was on S1:Standard Plan with No of units increased to 5, so, 2,000,000 messages/day 

The testing was done on 2 separate days.

**Comment by danhellem** [comment] 2021-11-29 17:37
@gitnwana ok interesting. Sounds more like a throttling issue with IoT Hub. I will go ahead and try and duplicate this over the next couple of days.

FYI @vishnureddy17

**Comment by gitnwana** [comment] 2021-11-29 17:41
Sure, Thanks. @danhellem

**Comment by danhellem** [comment] 2021-11-29 18:22
@vishnureddy17 I was able to repro this after about 3-5 minutes. I changed the interval to 10 miliseconds.

```javascript

function connectHandler () {
  console.log('Client connected');
  // Create a message and send it to the IoT Hub every two seconds
  if (!sendInterval) {
    sendInterval = setInterval(() => {
      const message = generateMessage();
      console.log('Sending message: ' + message.getData());
      client.sendEvent(message, printResultFor('send'));
    }, 10);
  }
}

```

Thoughts?

**Comment by danhellem** [comment] 2021-11-29 18:31
@gitnwana we are able to reproduce and our engineers are looking into. It will take some time as the issue is intermittent which makes it fun to track down. We will be in touch.

**Comment by gitnwana** [comment] 2021-11-29 19:11
Thanks @danhellem .

**Comment by avirup171** [comment] 2021-12-02 15:41
Hi. I faced a similar issue while load testing IoT hub. Any updates on this?

**Comment by danhellem** [comment] 2021-12-02 18:37
@avirup171 we just discovered the issue a couple days ago and it's on our list. As noted, it will take some time to figure this out. No news yet.

**Comment by danhellem** [comment] 2021-12-14 21:54
Based on our investigation, this appears to be an issue with you being throttled by IoT Hub. We are guessing you are shoving a bunch of telemetry into the pipeline in a short amount of time, and you begin to hit the throttling limits. We recommend you put a space (time) inbetween messages. That should help.

**Closed by danhellem** 2021-12-14 21:54 UTC
Labels: question, IoTSDK

**Comment by gitnwana** [comment] 2021-12-17 13:46
@danhellem , we are indeed putting lot of telemetry in the pipeline in a short amount of time as part of our load testing process. As for increasing the gap, I have tried the same with increase time 100ms, but it just delays the inevitable it seems.
