### ISSUE TITLE
Device SDK support for MQTT over WS behind proxy

### ISSUE THREAD

**Issue by pguptax** [Azure/azure-iot-sdk-node#394] opened 2018-10-12 20:52 UTC
When using https proxies in network, devices using node device sdk are not able to honor that proxy and thus not able to connect to IoT Hub.
We are using mqtt over ws.
I see following post that mentions support for proxies
https://azure.microsoft.com/en-us/blog/benefits-of-using-the-azure-iot-sdks-in-your-azure-iot-solution/
There is also information regarding C# sdk
https://github.com/Azure/azure-iot-sdk-csharp/issues/477
Can you advise the state of proxy support on Node device SDK.

**Comment by pierreca** [comment] 2018-10-18 00:15
Looking at the code and some details on how to support proxy settings in Node, i'm thinking it may already be supported:

First, it seems we support passing an agent down to the websocket layer (using setOptions):
https://github.com/Azure/azure-iot-sdk-node/blob/master/common/transport/mqtt/src/mqtt_base.ts#L232

Second, it looks like agents are the way the *ws* package supports proxies:
https://github.com/websockets/ws/#how-to-connect-via-a-proxy

Third, the *ws* package is what *mqttjs* depends on which is what we depend on.

So the feature might already be there... just not thoroughly documented as such. Needs to be confirmed though, and I don't have a readily available proxy to test this. The code would look something like this:

```js
var HttpsProxyAgent = require('https-proxy-agent');
var Client = require('azure-iot-device').Client;
var MqttWs = require('azure-iot-device-mqtt').MqttWs;

var client = Client.fromConnectionString('<connection string>', MqttWs);
client.setOptions({
  mqtt: {
    webSocketAgent: new HttpsProxyAgent(process.env.http_proxy) // YMMV depending on your proxy settings, it could also be a SocksProxyAgent instead.
  }
}, function (err) {
   //...
});

```


@pguptax do you have a test proxy you could try that with?

**Comment by pierreca** [comment] 2018-10-24 20:43
@pguptax FYI I finally had time to set up a local proxy to test the piece of code I was suggesting in my previous comment and it works. closing this issue as resolved.

**Comment by az-iot-builder-01** [comment] 2018-10-24 20:43
@pguptax, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2018-10-24 20:43 UTC
Labels: enhancement

**Comment by Sebs030** [comment] 2019-02-07 09:30
Just for reference if facing the issue with http(s), which i stumbled upon until I had been pointed to this issue:
``` js
const HttpsProxyAgent = require('https-proxy-agent');
const Client = require('azure-iot-device').Client;
const  Protocol = require('azure-iot-device-mqtt').Http;

var client = Client.fromConnectionString('<connection string>', Protocol);
// then in the client.open(callback) call
client.setOptions({
      http: {
        agent: new HttpsProxyAgent(<"Your proxy server goes here">)
      }
    }, function (err) {
       //
    });
