### ISSUE TITLE
TypeError: Cannot set property 'subscribeInProgress' of undefined

### ISSUE THREAD

**Issue by gtrifonov** [Azure/azure-iot-sdk-node#282] opened 2018-04-25 03:53 UTC
# Context
- **OS and version used:**  Raspbian stretch
- ** Docker :** Docker version 18.04.0-ce, build 3d479c0
- **Node.js version:** v8.11.1
- **npm version:** 6.0.0
- **list of installed packages:** sudo npm list | grep "iot" 
├─┬ azure-iot-device@1.4.0-modules-preview
│ ├── azure-iot-common@1.5.0-modules-preview
│ ├─┬ azure-iot-http-base@1.3.3-modules-preview
│ │ ├── azure-iot-common@1.5.0-modules-preview deduped
├─┬ azure-iot-device-mqtt@1.4.0-modules-preview
│ ├── azure-iot-common@1.5.0-modules-preview deduped
│ ├── azure-iot-device@1.4.0-modules-preview deduped
│ ├─┬ azure-iot-mqtt-base@1.3.3-modules-preview
│ │ ├── azure-iot-common@1.5.0-modules-preview deduped

# Description of the issue:
Getting error after iothub connection is opened when running docker edge module.

/app/node_modules/azure-iot-device-mqtt/lib/mqtt.js:682
        topic.subscribeInProgress = true;
                                  ^

TypeError: Cannot set property 'subscribeInProgress' of undefined
    at Mqtt._setupSubscription (/app/node_modules/azure-iot-device-mqtt/lib/mqtt.js:682:35)
    at constructor.enableC2D (/app/node_modules/azure-iot-device-mqtt/lib/mqtt.js:294:31)
    at constructor.handle (/app/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (/app/node_modules/machina/lib/machina.js:466:63)
    at Mqtt.enableC2D (/app/node_modules/azure-iot-device-mqtt/lib/mqtt.js:534:19)
    at retryOp.retry._this._c2dEnabled (/app/node_modules/azure-iot-device/lib/client.js:551:34)
    at retryOperation (/app/node_modules/azure-iot-common/lib/retry_operation.js:31:13)
    at RetryOperation.retry (/app/node_modules/azure-iot-common/lib/retry_operation.js:57:9)
    at Client._enableC2D (/app/node_modules/azure-iot-device/lib/client.js:550:21)
    at Client.<anonymous> (/app/node_modules/azure-iot-device/lib/client.js:101:23)

# Code sample exhibiting the issue:
code from iot-hub sample. only difference is that connection string is populated from edge env variable -EdgeHubConnectionString.  
"EdgeHubConnectionString=HostName=xxx;GatewayHostName=xxx;DeviceId=pi3;ModuleId=v6;SharedAccessKey=xxxxxx"

# Console log of the issue:
/app/node_modules/azure-iot-device-mqtt/lib/mqtt.js:682
        topic.subscribeInProgress = true;
                                  ^

TypeError: Cannot set property 'subscribeInProgress' of undefined
    at Mqtt._setupSubscription (/app/node_modules/azure-iot-device-mqtt/lib/mqtt.js:682:35)
    at constructor.enableC2D (/app/node_modules/azure-iot-device-mqtt/lib/mqtt.js:294:31)
    at constructor.handle (/app/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (/app/node_modules/machina/lib/machina.js:466:63)
    at Mqtt.enableC2D (/app/node_modules/azure-iot-device-mqtt/lib/mqtt.js:534:19)
    at retryOp.retry._this._c2dEnabled (/app/node_modules/azure-iot-device/lib/client.js:551:34)
    at retryOperation (/app/node_modules/azure-iot-common/lib/retry_operation.js:31:13)
    at RetryOperation.retry (/app/node_modules/azure-iot-common/lib/retry_operation.js:57:9)
    at Client._enableC2D (/app/node_modules/azure-iot-device/lib/client.js:550:21)
    at Client.<anonymous> (/app/node_modules/azure-iot-device/lib/client.js:101:23)

**Comment by pierreca** [comment] 2018-04-25 17:59
cloud-to-device is not supported in the modules preview, that's why it's crashing. this being said, we should provide a better error message. we've been looking into providing a better API shape. I'm closing this for now because it's unlikely we'll fix this code "as is" (and more likely we'll rework the API surface).

**Closed by pierreca** 2018-04-25 17:59 UTC
Labels: investigation-required

**Comment by pierreca** [comment] 2018-06-14 00:49
@gtrifonov 
thank you for your contribution to our open-sourced project! Please help us improve by filling out [this 2-minute customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).

**Comment by shaneholder** [comment] 2021-08-04 01:08
This still seems to be an issue, is there a new way to send C2D messages to a module?

**Comment by erikmetzinfo** [comment] 2021-09-14 22:00
> This still seems to be an issue, is there a new way to send C2D messages to a module?

Same issue here

**Comment by BertKleewein** [comment] 2021-09-15 17:04
@shaneholder and @erikmetzinfo - Unfortunately, there is no way to send a C2D to a module.  You could use module twins or direct methods to implement the behavior you want, or you could send C2D to your IoT Edge device and use message routing to send this to the module using a module input.

**Comment by shaneholder** [comment] 2021-09-15 18:33
@BertKleewein when you say there is no way to send a C2D message to a module, perhaps we are talking semantics here.  

Take a look at #1016.  I can *send* a message to a C2D node module, it's just not received at the device layer, it shows up in MQTT.  Also the C# SDK has the ability to receive a message from the ModuleClient.  So can you elaborate a bit on your statement please?

Also there doesn't seem to be a distinction in the node SDK (not looked at the C# SDK) between IoT Edge and IoT Devices.  Currently I'm using IoT devices but investigating Edge usage.

Thanks,
Shane

**Comment by BertKleewein** [comment] 2021-09-15 19:39
I agree that the landscape and terminology are both confusing.  If I were working alone, I would not have designed things this way, but this is what we have.  The short answer is:

Yes, some of the functionality looks like it's there.  It probably works in some scenarios.  It's not an official feature.  Officially speaking, modules do not support C2D.

The module client was designed to be used with module identities.  The device client was designed to be used with device identities.  There is some unfortunate confusion because using a module with IoT Edge gives you some extra functionality (method invoke, inputs, and outputs), and these functions are on the module client even if you're not using IoT Edge.  I personally wish we had 3 different clients because of these extra functions, but we don't.  

Also, because there is so much overlap between the way that devices and modules work, you can do things like use a device client with a module identity, or a module client with a device identity.   Most features will probably work, but maybe not, and probably not everything

I wish the answer were clearer but it's the best I can do.

**Comment by shaneholder** [comment] 2021-09-17 14:59
@BertKleewein when you say "Officially speaking, modules do not support C2D" are you just speaking about the node SDK? The C# SDK clearly has a way to send and receive messages to a module.

The ServiceClient has:
```
public abstract Task SendAsync(string deviceId, string moduleId, Message message);
```

Thanks again for your help.

**Comment by shaneholder** [comment] 2021-09-20 13:48
Replying to @YoDaMa here,

Yes please.  There is confusion in the different language SDK's, as I mentioned the C# SDK implies that messaging to Modules is a supported function.  

Regards,
Shane

**Comment by YoDaMa** [comment] 2021-09-20 13:56
@shaneholder, we will sync cross team to investigate what you're saying. that would mean we have inconsistencies. but to echo what @BertKleewein has said and what I have also said, you're right in seeing that Node.js SDK does not support C2D to modules. It is because Edge Hub dictates what we should, and should not support, and based on the Edge Hub requirements, we do not support C2D. 

I'd recommend you take the further comments to https://github.com/Azure/azure-iot-sdk-node/issues/1016, since this is a long closed issue.
