### ISSUE TITLE
Uncaught Exception thrown after the error message is emitted - amqp errors

### ISSUE THREAD

**Issue by maestroblue** [Azure/azure-iot-sdk-node#778] opened 2020-05-04 17:07 UTC
# Context

- **OS and version used:** Windows 10
- **Node.js version:** 10.19.0
- **npm version:** 6.13.4
- **list of installed packages:**

- **cloned repo:** (used iot sdk packages):
"azure-iot-common": "1.11.2"
"azure-iot-device": "1.12.2"
"azure-iot-device-amqp": "1.11.2"
"azure-iot-device-http": "1.11.2"

## Description of the issue

We use amqpWS for out IoT connection protocol in our nodeJs codebase. However, there are certain amqp errors we have been encountering. There are two ways that we run into them. The recently observed one is that once the error listener attached to the iot client catches the error, and we start closing the client & removing the references/listeners on it, within the same second the main process throws an uncaught exception (We attach error, disconnect and message listeners to the iot client). The first example happens when we are calling client.open() - I'm not sure if the callback passed to this method is invoked or if it is invoked with success, but the error is caught by the listener.

The error caught is:

```js
 { Error: AMQP Transport: Could not connect
    at Object.translateError (C:\Program Files\Avigilon\Avigilon Control Center Web Endpoint\node_modules\azure-iot-amqp-base\lib\amqp_common_errors.js:104:17)
    at C:\Program Files\Avigilon\Avigilon Control Center Web Endpoint\node_modules\azure-iot-device-amqp\lib\amqp.js:294:105
    at C:\Program Files\Avigilon\Avigilon Control Center Web Endpoint\node_modules\azure-iot-amqp-base\lib\amqp.js:769:51
    at process._tickCallback (internal/process/next_tick.js:61:11)
  amqpError:
   { NotConnectedError: rhea: connection disconnected name: 'NotConnectedError' } }
```
We also have a listener on the process for uncaughtException, and in the same second we get this:

```js
2020-04-15 16:36:56 error: uncaughtException: AMQP Transport: Could not connect
Error: AMQP Transport: Could not connect
    at Object.translateError (C:\Program Files\Avigilon\Avigilon Control Center Web Endpoint\node_modules\azure-iot-amqp-base\lib\amqp_common_errors.js:104:17)
    at C:\Program Files\Avigilon\Avigilon Control Center Web Endpoint\node_modules\azure-iot-device-amqp\lib\amqp.js:294:105
    at C:\Program Files\Avigilon\Avigilon Control Center Web Endpoint\node_modules\azure-iot-amqp-base\lib\amqp.js:769:51
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
and it crashes our application.

The other instance of this issue is observed while we are sending the first message to IoT (so open was successful, and we were invoking client.sendEvent()). The error listener got:

```js
2020-04-23 01:12:07 error: [cloudClient-iotClient] error received from iotHub, closing the connection: c {
  value:
   [ Typed { type: [TypeDesc], value: 'amqp:internal-error' },
     Typed {
       type: [TypeDesc],
       value: 'Another AMQP Client has opened a Receive Link' },
     Typed { type: [TypeDesc], value: null } ] }
```

And then as we are cleaning the state as detailed above, we get the following: 

```js
2020-04-23 01:12:07 error: uncaughtException: Unhandled error. (c {
  value:
   [ Typed { type: [TypeDesc], value: 'amqp:internal-error' },
     Typed {
       type: [TypeDesc],
       value: 'Another AMQP Client has opened a Receive Link' },
     Typed { type: [TypeDesc], value: null } ] })
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (c {
  value:
   [ Typed { type: [TypeDesc], value: 'amqp:internal-error' },
     Typed {
       type: [TypeDesc],
       value: 'Another AMQP Client has opened a Receive Link' },
     Typed { type: [TypeDesc], value: null } ] })
    at IotClient.emit (events.js:187:17)
    at IotClient._onError (C:\Program Files\Avigilon\Avigilon Control Center Web Endpoint\modules\cloud-client\lib\IotClient.js:627:10)
```

One thing worth noting is that in the listener we set a boolean for the IoT client instance (which there should only be 1 at any given time in our business logic) that if the error handler got an error, we ignore the other ones we get. We still catch them in our handler but because we are in the process of destroying that instance at that point, we just discard it. I am not sure if this would cause this behavior though.

The second and more frequently observed pattern amqp errors is that we get a lot of random amqp errors, of different types. We handle all these errors in the same way - destroy the instance and the connection, and wait for the service that manages the state to initiate the connection from scratch. Below is two other amqp errors we observe within this pattern. The most common error thrown is the being the first error type I shared above ( { NotConnectedError: rhea: connection disconnected name: 'NotConnectedError' } ). The most challenging part about these errors is that we cannot reproduce them ( or know the steps to reproduce them), as they sporadically happen in production.

```js
2020-04-07 13:24:16 warn: [cloudClient-connectionManager] error received from iotClient: {"transportObj":{"amqpError":{"condition":"amqp: link:detach-forced","description":"Server Busy. Please retry operation"}}}
```

and 

```js
2020-03-21 23:45:05 error: [cloudClient-connectionManager] error in stop iot client:  { Error: error while detaching the D2C link when disconnecting
    at Object.translateError (/opt/edge/avigilon.acc.webendpoint/node_modules/azure-iot-amqp-base/lib/amqp_common_errors.js:104:17)
```
I guess the issue is, are these errors occuring because of a malpractice on our end? Is there a way to figure out what the problem is (as it has been hard to understand why). 

Lastly, this might require another ticket spin off, but sometimes we have observed that D2C messages will make it to the cloud, but C2D messages never reach to the device (while D2C is still working). I am not sure if this has to do with the state of the sdk on the device, or is an issue on the cloud side. 

Thank you very much for your time! 

AB#7366643

**Comment by anthonyvercolano** [comment] 2020-05-04 17:57
There is a lot going on here.  I will try to go over this a bit more later when I can closely read your post.

The issue where the error is complaining about another client opening is likely to be caused on your side.  A device can't be opened by two different clients at the same time.  How that shows up (especially perhaps in your recovery situation is difficult.)

The problem where you see d2c continuing (likely after some sort of error recovery) but c2d no longer works is likely a bug on our part.   Hard to reproduce, but I've seen it before.  Could at its root level be caused by transient network issues OR the service moving processing between nodes.

We will look at this closely.  However, I need to set your expectations here.  Not likely to see something on this before mid-June.

I will try to comment more tomorrow.

**Comment by gulipek95** [comment] 2020-05-04 18:09
Thank you very much for your fast response!

We are doing some cleanups in our code as we see some parts that need improvements, but the biggest confusion for us is the (same) error being thrown after the handler catching it the first time. Will try my best to provide any clarifications/further details should you need them. 

I appreciate the timeline provided, I will propagate that to the team. Looking forward to it!

**Comment by alexjavarotti** [comment] 2020-06-18 18:54
We re facing   a similar problem, considering the stack trace part "**/app/node_modules/azure-iot-device-amqp/lib/amqp.js:294:105**". 

_"azure-iot-common": "1.10.2",
"azure-iot-device": "1.11.2",
"azure-iot-device-amqp": "1.10.3",
"azure-iot-provisioning-device": "1.6.3",
"azure-iot-provisioning-device-amqp": "1.6.3",
"azure-iot-security-x509": "1.5.12",_

```
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01`    |   [length]: 38 ]
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    | 2020-06-18T18:22:28.498Z [proxy:authentication] debug: Adding a password for module edge-proxy
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    | [connection-1] disconnected [object Object]
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    | 2020-06-18T18:22:28.512Z [proxy:retryPolicy] error: Encountered unrecoverable error: Error: AMQP Transport: Could not connect
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    | Error: AMQP Transport: Could not connect
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    |     at Object.translateError (/app/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp_common_errors.js:104:17)
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    |     at /app/node_modules/azure-iot-device-amqp/lib/amqp.js:294:105
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    |     at /app/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp.js:769:51
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    |     at process._tickCallback (internal/process/next_tick.js:61:11)
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    | 2020-06-18T18:22:28.512Z [proxy:deviceClient] error: Device client threw an error: Error: AMQP Transport: Could not connect
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    | 2020-06-18T18:22:28.512Z [proxy] error: Unhandled exception: AMQP Transport: Could not connect
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    | Error: AMQP Transport: Could not connect
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    |     at Object.translateError (/app/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp_common_errors.js:104:17)
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    |     at /app/node_modules/azure-iot-device-amqp/lib/amqp.js:294:105
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    |     at /app/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp.js:769:51
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    |     at process._tickCallback (internal/process/next_tick.js:61:11)
edge-proxy.1.9wxrngdkokei@BrAssetVistaEdge01    | 2020-06-18T18:22:28.513Z [proxy:edgeProxy] verbose: Received request to stop the proxy
```
Is there any new information about that issue ?

**Comment by YoDaMa** [comment] 2020-06-23 17:26
@alexjavarotti, I don't know how your issue is related to this issue. From your log snippet, you seem to be hitting errors, but there's no uncaught errors. It is `AMQP Transport: Could not connect`. Seems like you're just... not connecting. Maybe an issue with your credentials?

**Comment by YoDaMa** [comment] 2021-02-26 23:50
closing this issue since no further updates on status. Feel free to open a new issue if problems are persisting.

**Closed by YoDaMa** 2021-02-26 23:50 UTC
Labels: IoTSDK, bug, investigation-required
